version: "3.8"

services:
  backend:
    build: ./backend
    image: vshnv2001/blockhouse:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=blockhouseuser
      - POSTGRES_PASSWORD=blockhouse
      - POSTGRES_DB=blockhouse-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
