name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest Docker images
      run: |
        sudo docker pull vshnv2001/blockhouse:latest
        sudo docker pull postgres:15  # Pull the required database image

    - name: Stop and Remove Old Containers
      run: |
        sudo docker compose down || true
        sudo docker system prune -af  # Clean up old containers and unused images

    - name: Run Containers with Docker Compose
      run: |
        sudo docker compose up -d
